: > "./data/accounts.dat"
: > "./data/profiles.dat"
: > "./data/PendingRequests.dat"
cat "./tests/indexed_base_data.txt" > "./data/EstablishedConnections.dat"
cat "./tests/indexed_base_data.txt" > "./data/PendingRequests.dat"
: > "./data/JobPostings.dat"
: > "./data/JobApplications.dat"
: > "./data/Messages.dat"