>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. InCollege.

DATA DIVISION.
WORKING-STORAGE SECTION.

77 WS-APP-SHOULD-QUIT PIC X VALUE "N".
77 WS-MAIN-MENU-INPUT PIC X VALUE SPACE.
77 WS-TOTAL-SAVED-ACCTS PIC 9(2) VALUE 0.
77 WS-CREDENTIALS-L PIC X VALUE SPACE.
77 WS-CREDE PIC X VALUE SPACE.

01 WS-STORED.
   05 WS-STORED-USERNAME PIC X(10) OCCURS 10 TIMES VALUE SPACES.
   05 WS-STORED-PASSWORD PIC X(20) OCCURS 10 TIMES VALUE SPACES.

01 WS-PROFILE-LIST.
   05 WS-PROF-ROW OCCURS 10 TIMES.
      10 Username PIC X(10) VALUE SPACES.
      10 Name PIC X(25) VALUE SPACES.
      10 University PIC X(25) VALUE SPACES.
      10 Major PIC X(25) VALUE SPACES.
      10 GradYear PIC X(4) VALUE SPACES.
      10 About PIC X(200) VALUE SPACES.
      10 JobTitle PIC X(25) VALUE SPACES.
      10 Company PIC X(25) VALUE SPACES.
      10 Dates PIC X(15) VALUE SPACES.
      10 Desc PIC X(100) VALUE SPACES.
      10 Degree PIC X(25) VALUE SPACES.
      10 Univ PIC X(25) VALUE SPACES.
      10 Years PIC X(15) VALUE SPACES.

77 WS-PROFILE-COUNT PIC 9(2) VALUE 0.
77 WS-CURRENT-USER PIC X(10) VALUE SPACES.

77 WS-CREATE-SUCCESS PIC X VALUE "N".
77 WS-LOGIN-SUCCESS PIC X VALUE "N".

PROCEDURE DIVISION.
MAIN-FLOW.
    PERFORM UNTIL WS-APP-SHOULD-QUIT = "Y"
        DISPLAY "Welcome to InCollege!"
        DISPLAY "1) Log In"
        DISPLAY "2) Create Account"
        DISPLAY "3) Exit"
        DISPLAY "Choose an option: "
        ACCEPT WS-MAIN-MENU-INPUT

        EVALUATE WS-MAIN-MENU-INPUT
            WHEN "1"
                CALL "LogIn" USING WS-STORED WS-TOTAL-SAVED-ACCTS WS-CURRENT-USER WS-LOGIN-SUCCESS
                IF WS-LOGIN-SUCCESS = "Y"
                    CALL "HomePage" USING WS-CURRENT-USER WS-PROFILE-LIST WS-PROFILE-COUNT
                END-IF
            WHEN "2"
                CALL "CreateAccount" USING WS-STORED WS-TOTAL-SAVED-ACCTS WS-CREATE-SUCCESS
            WHEN "3"
                MOVE "Y" TO WS-APP-SHOULD-QUIT
            WHEN OTHER
                DISPLAY "Invalid option. Try again."
        END-EVALUATE
    END-PERFORM
    STOP RUN.