IDENTIFICATION DIVISION.
PROGRAM-ID. ProfileEdit.

DATA DIVISION.
WORKING-STORAGE SECTION.
77 DUMMY PIC X VALUE 'N'.

LINKAGE SECTION.
01 LNK-USER-NAME PIC X(30).
77 LK-PROFILE-COUNT PIC 9.
01 LK-PROFILE-LIST.
    05 LK-PROF-ROW OCCURS 5 TIMES.
        10 LK-USERNAME    PIC X(30).
        10 LK-NAME        PIC X(50).
        10 LK-UNIVERSITY  PIC X(50).
        10 LK-MAJOR       PIC X(50).
        10 LK-GRADYEAR    PIC 9(4).
        10 LK-ABOUT       PIC X(200).
        10 LK-JOBTITLE    OCCURS 3 TIMES PIC X(50).
        10 LK-COMPANY     OCCURS 3 TIMES PIC X(50).
        10 LK-DATES       OCCURS 3 TIMES PIC X(30).
        10 LK-DESC        OCCURS 3 TIMES PIC X(200).
        10 LK-DEGREE      OCCURS 3 TIMES PIC X(50).
        10 LK-UNIV        OCCURS 3 TIMES PIC X(50).
        10 LK-YEARS       OCCURS 3 TIMES PIC X(30).

PROCEDURE DIVISION USING LNK-USER-NAME LK-PROFILE-COUNT LK-PROFILE-LIST.

MAIN.
    CALL "ProfileCreate" USING LNK-USER-NAME LK-PROFILE-COUNT LK-PROFILE-LIST
    DISPLAY "Profile saved successfully."
    GOBACK.

END PROGRAM ProfileEdit.